use crate::text;
use rand::{rng, seq::IndexedRandom};
use teloxide::{prelude::*, types::ParseMode};
pub async fn run(bot: Bot, msg: Message) -> ResponseResult<()> {
    let r = *MEOW_TEXTS.choose(&mut rng()).unwrap();
    text!(bot, msg, r, ParseMode::Html).await?;
    Ok(())
}

const MEOW_TEXTS: [&str; 132] = [
    "Meow! 🐾",
    "Purrrr...",
    "Feed me, human! <i>Now!</i>",
    "Where's my nap spot? 😴",
    "Miaow?",
    "I require pets. *Immediately*. ✨",
    "Is that... tuna? 🐟",
    "Staring intently... 👀",
    "<i>*knocks something off the table*</i> Oops.",
    "Mrow? 🤔",
    "Let me outside... no, wait, inside! <strike>Make up your mind!</strike>",
    "I knead this blanket... and maybe <b>your</b> leg. 🧶",
    "The red dot! Where did it go?! 🔴",
    "Ignoring you is my cardio. 😼",
    "Sleeping in a sunbeam. ☀️",
    "Bring me shiny things! ✨",
    "My bowl is... <i>tragically</i> empty. 😩",
    "Hiss! (Just kidding... maybe. 😈)",
    "Presenting my belly... <b>it's a trap!</b>",
    "Zoomies commencing in 3... 2... 1... 💥",
    "Prrrrt?",
    "Meow meow! 🎶",
    "Mrrrrraw! <pre>Loudly.</pre>",
    "Did I hear the fridge open? 🧊",
    "I require attention. <b>Immediately</b>. 🚨",
    "Eeeeeek! (a mouse!) 🐭",
    "Just woke up from an 18-hour nap. What year is it? 🕰️",
    "Head boop! ❤️",
    "Did someone say... <i>treats</i>? 🎁",
    "You woke me up... now suffer my wrath! 😾",
    "Your bed? Nope. Mine now. 👑",
    "I knocked it over because I love you. (...and it was in the way).",
    "I'm majestic. Worship me. 🙏",
    "I saw a bird once. Still not over it. 🐦",
    "Let's play! No—too much. I'm biting now. 😬",
    "This tail? It's trying to get me! 😱",
    "You moved? Betrayal. 😭",
    "I rule this house. You just pay the bills. 🏰",
    "Laser pointer or sorcery? 🧙‍♂️",
    "Don't touch the tummy. Seriously. 🚫",
    "Did I just see another cat?! Intruder! ⚔️",
    "What's this button do? *boop* 🖱️",
    "I'll sit here. Right on your keyboard. ⌨️",
    "No thoughts. Just meows. <pre>empty head</pre>",
    "I meow, therefore I am. 🤔",
    "That noise was suspicious. Panic mode engaged. 😨",
    "It's 3 AM. Let’s party! 🎉",
    "I bring chaos and fur. Deal with it. 😎",
    "Time to destroy the toilet paper. 🧻",
    "Window open? Instant birdwatching! 📺",
    "Sniff... ew. Sniff again. 🤔",
    "Did you say... <code>vet</code>?! 🏥 Nooooo!",
    "My tail is alive! It has a mind of its own!",
    "This box shrank... not me. 📦",
    "I'm fast. You're slow. Try to catch me! 💨",
    "Don't mind me—I'm just judging you. 🧐",
    "Hooman, fix the blanket folds. It's suboptimal.",
    "I demand tribute in the form of treats. 💰",
    "My purring is <b>not</b> consent to belly rubs.",
    "Silently plotting your next nap spot invasion.",
    "Attack the foot. Retreat. Repeat. ⚔️",
    "Is the food bowl half empty or half full? Either way, MORE! 🍽️",
    "My elegance is only matched by my capacity for mischief. ✨😈",
    "Chirp! Trill! Meeeow! 🦜",
    "Yawn... big stretch! Ready for my next nap.",
    "Rubbing against your legs. That means feed me. Or pet me. Or both. Or maybe I'm just marking my property.",
    "Staring into the void... or maybe just at a particularly interesting wall texture. 🧱",
    "That plant looked suspicious. Had to investigate with my teeth. 🪴 Bite!",
    "Cleaning my paws meticulously. One must maintain standards. Especially toe beans. ✨🐾",
    "Followed you into the bathroom. I'm your official Potty Supervisor now. 👀🚽",
    "Making biscuits on the air. Practicing my dough technique. 👨‍🍳 Maybe later on your chest.",
    "My purr motor is running smoothly. Calibrated for maximum soothing... or annoyance. Vroom vroom. 🚗",
    "If I fits, I sitz. Even if 'fits' is debatable. 📐<0xC2><0xA0>precarious_cat",
    "The sound of a can opener is the siren song of my people. 🥫❤️ Answer the call!",
    "Grooming interrupted by... existential dread! Or maybe just a hairball incoming. 🤢",
    "Talking back to the birds outside. They gossip too much. 🗣️🐦",
    "Is this lap occupied? Doesn't matter. Claimed. Resistance is futile.",
    "Paw under the door. Just checking if you're still alive... and if that door leads to snacks. 🚪🐾",
    "Smacked the dog gently (or not so gently). Asserting my place in the hierarchy. 🐶👑",
    "Curiosity didn't kill the cat, it just made me knock over your expensive vase.",
    "Rolling around on the floor in ecstasy. Why? Because floor. That's why. 🤪",
    "My meow is music. Appreciate my avant-garde symphony. 🎼 Sometimes it's opera.",
    "Brought you a 'gift'. It's a bottle cap. Cherish it. You're welcome. 👑",
    "My ears are twitching independently. Processing multiple data streams... mostly sounds of potential food packaging. 👂📡",
    "Slow blink. That means I acknowledge your presence without hostility... probably. 😉",
    "Hiding under the furniture. It's my secret lair. No humans allowed (unless bringing treats). 🏰",
    "Climbing the curtains. Because Everest is too far away and less satisfyingly shreddable. 🏔️",
    "Licking plastic bags. Don't ask why. It's a complex flavor profile. 🛍️👅 Science!",
    "I demand entry to the forbidden closet! What secrets does it hold? Socks? Monsters? Both? 🚪🗝️",
    "Sniffing your shoes intently. Where have you BEEN, human? What other animals did you pet?! 👟🕵️ Betrayal!",
    "Sharpening claws on the forbidden sofa. It feels... necessary. A primal urge. 🛋️🔪",
    "A single, plaintive 'mew'. Translate it as 'I desire an unspecified service immediately'.",
    "I am liquid. Watch me pour myself into this impossibly small container. 💧📦 Physics is optional.",
    "The water bowl is full, but the forbidden allure of the dripping faucet is superior. 💧👑 Freshness!",
    "Suddenly stopping mid-zoom to groom intensely. Must maintain dignity amidst chaos. ✨",
    "Chattering at the window. Those squirrels mock my very existence! Must... plot... revenge! 🐿️💢",
    "Presenting my backside. It's a sign of trust. Or I just don't want to look at you right now. 🍑",
    "I require a box. Any box. The smaller and more inconvenient, the better. Provide one NOW. 📦",
    "Muffled meow from under the duvet. Send snacks and perhaps a small oxygen tank.",
    "Woke up. Chose violence (playful, yet painful, ankle biting). 😬 It's morning!",
    "I walk this path. Right across your keyboard. As is tradition. Do not question the ancient ways. 🚶‍♀️⌨️",
    "My whiskers brushed against it. Therefore, under feline law, it is mine. Property claimed. ✨",
    "Staring at a blank wall like it holds the secrets of the universe. Maybe it does.",
    "Paw dipped in your water glass. Just testing the temperature. And maybe adding flavor.",
    "Tail twitching erratically. Warning: May pounce on anything (or nothing) without notice.",
    "Sitting in the loaf position. Maximum coziness achieved. 🍞",
    "Letting out a tiny 'mew' that somehow conveys immense suffering and starvation. Feed me.",
    "Calculated jump... miscalculated landing. *Thump*. I meant to do that.",
    "Eyes wide, pupils dilated. Engaging 'hunter mode' for... a dust bunny.",
    "Rubbing my face on the corner of your laptop. Needs more cat scent.",
    "Digging frantically in the litter box like I'm searching for buried treasure. 🏴‍☠️💎",
    "Ignoring the expensive cat bed to sleep on a pile of dirty laundry. It smells like... victory. 🧺",
    "Why are you typing? You should be petting. Realign your priorities.",
    "Batting at your dangling phone charger. It looks like a snake. A fun snake. 🐍",
    "Chirping sound activated. Usually reserved for birds or intense focus.",
    "Stretching... s-t-r-e-t-c-h-i-n-g... okay, nap time again.",
    "Running sideways with arched back. Crab cat mode engaged! 🦀",
    "I smell food. Somewhere. I will find it. And I will sit near it expectantly. 👃",
    "Licking my nose. System check complete. Ready for... whatever.",
    "Is that... catnip? 👀🌿 The good stuff?",
    "Making eye contact, then slowly pushing something off the edge. Defiance.",
    "Meow? Meeeow! MROW! (Translation: Varies, but probably involves food or attention).",
    "Sitting in the sink. It's cool. It's concave. It's perfect.",
    "Watching the washing machine spin. Mesmerizing. 😵‍💫",
    "Can I have some of that? Whatever you're eating. Sharing is caring. Give it.",
    "Just remembered I have a tail. *pounce*",
    "Current mood: inscrutable.",
    "I tolerate your presence. Barely.",
    "Scratching the door frame. Just leaving my signature. ✍️",
    "I have trained my human well. They know the meaning of the stare. 👀",
    "The sound of kibble hitting the bowl: music to my ears. 🎶",
    "Meow.",
];
